services:
webmin:
    image: johanp/webmin
    networks:
      - frontend

  sshuser:
    build: ./sshuser
    depends_on:
      - jumphost
    networks:
      - frontend

  jumphost:
    build: ./jumphost
    ports:
      - "2222:22"
    networks:
      - frontend
      - backend

  target:
    build: ./target
    depends_on:
      - jumphost
    ports:
      - "2223:22"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
