services:
  webmin:
    image: johanp/webmin
    networks:
      - frontend
  sshuser:
    build: ./sshuser
    depends_on:
      - jumphost
    networks:
      - office
  jumphost:
    build: ./jumphost
    networks:
      - frontend
      - backend
      - office
  target:
    build: ./target
    depends_on:
      - jumphost
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  office:
    driver: bridge