services:
  # webmin:
  #   build: ./webmin
  #   ports:
  #     - "10000:10000"
  #   networks:
  #     - frontend
  ssh_user:
    build: ./ssh_client
    env_file:
      - .env
    volumes:
      - ./ssh_client/.ssh/:/root/.ssh/
    depends_on:
      - jumphost
    networks:
      - office
    entrypoint: /usr/local/bin/entrypoint.sh
  jumphost:
    build: ./jumphost
    env_file:
      - .env_pub
    volumes:
      - ./jumphost/authorized_keys:/root/.ssh/authorized_keys
    networks:
      - frontend
      - backend
      - office
    environment:
      - PUB=${PUB}
  target:
    build: ./target
    env_file:
      - .env_pub
    environment:
      - PUB=${PUB}
    volumes:
      - ./target/authorized_keys:/root/.ssh/authorized_keys
    depends_on:
      - jumphost
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  office:
    driver: bridge
